### ISSUE TITLE
Trojan

### ISSUE THREAD

**Issue by pkp24** [louisgv/local.ai#100]
My antivirus terminated mid install for it being a trojan

Event: Process terminated
Application: Local.AI_0.6.4_x64-setup.exe
Component: System Watcher
Result description: Terminated
Type: Trojan
Name: PDM:Trojan.Win32.Generic
Threat level: High
Object type: Process
Object name: Local.AI_0.6.4_x64-setup.exe

**Comment by navr32** [comment]
Please what is your Antivirus ? 
I have scan it at  Virustotal.com  just a probable malware was found...this can be false positive..more research are needed..

![image](https://github.com/louisgv/local.ai/assets/1823291/124925ee-ac36-420e-897d-cbab6ba7c7ee)

**Comment by pkp24** [comment]
It's tagged other stuff as not trojan but sus before. The fact that it tagged this as trojan is highly suspicious. My antivirus is Kaspersky

**Comment by louisgv** [comment]
You can build from source - the instruction is on README. The executable is for convenient but you can see the build process all in the github action workflow as well:

https://github.com/louisgv/local.ai/actions
