### ISSUE TITLE
Windows | New Thread does not do anything

### ISSUE THREAD

**Issue by vexersa** [louisgv/local.ai#101]
I've installed the latest version on Windows, when clicking New Thread nothing happens.
![Animation](https://github.com/louisgv/local.ai/assets/7994227/1b269d4b-3b9a-4671-bdac-be9e14554a6f)

**Comment by navr32** [comment]
Before be able to do new thread you must validate a good directory where the Threads will be record/save....
Or in your video you close the Filepicker without have set and validate the saving directory...
So until you have not set a good Directory where to save the data of the threads you can't create a new thread..
