### ISSUE TITLE
feat: stop inference mid-way

### ISSUE THREAD

**Issue by louisgv** [louisgv/local.ai#20]

**Comment by Regular-Baf** [comment]
I've just tried Red Pyjama 3B chat and it kinda got a bit lost...
![image](https://github.com/louisgv/local.ai/assets/95348524/05ed1dd5-e866-419f-857f-fba2e70eb4e2)
I think we need this too 😅

**Comment by louisgv** [comment]
Oh yeah with redpajama, we need remote vocab #7 #11
