### ISSUE TITLE
Sending a message to the server and receiving a response in an external application?

### ISSUE THREAD

**Issue by Regular-Baf** [louisgv/local.ai#30]
I think the whole idea behind having the user's computer handle the compute for AI-powered applications is quite awesome, so I've decided to try and build a Minecraft mod around it. The application seems to host a server, but I was just wondering how to correctly send and receive ?

**Comment by louisgv** [comment]
@Regular-Baf 
What language does the Minecraft mod use? The streaming server exposed by local.ai is a standard SSE completion endpoint, mirroring closely openai's API. LMK if you wanna jump on a call and we can jam on something this week.

**Comment by Regular-Baf** [comment]
I'm quite new to modding and programming in general so ChatGPT is doing the heavy lifting, but I'm writing the mod in Kotlin for Fabric. The code is all public [here](https://github.com/Regular-Baf/bafmod2). I spent a few hours today and I've managed to get some basic functionality down, but the replies from the model are very hit and miss, likely a prompt template issue. I'd be down to discuss this project more, my Discord is Bafmaster#2997, or let me know if there is a better place to reach you :)

**Comment by louisgv** [comment]
@Regular-Baf friend request sent on Discord!

**Comment by FernandoFerrer** [comment]
Could you please provide an exaple call to the SSE completion endpoint? I am trying to call it using Python requests and sseclient but not able to make it work. Thanks!

**Comment by louisgv** [comment]
@FernandoFerrer it's a similar API to openai, here's the js call: 

https://github.com/louisgv/local.ai/blob/main/apps/desktop/src/features/thread/use-active-thread.ts#L82-L114
https://github.com/louisgv/local.ai/blob/main/apps/desktop/src/features/thread/process-sse-stream.ts

It's a data stream `/completion` endpoint. Maybe you didn't include the `/completion`?

**Comment by FernandoFerrerTDK** [comment]
> 

Thank you very much! Following your example I was able to make it work :)

**Comment by louisgv** [comment]
I think it would be awesome if we have a simple example python project or something like a streamlit playground for folks to quickly test out the API call.

@FernandoFerrerTDK @Regular-Baf Would you be down publish an example github repo project? We can then link them in our github and frontpage as well. I know that @Regular-Baf got a working Kotlin client, and I think having both as an example would be huge!

**Comment by Regular-Baf** [comment]
Maybe a wiki page on local.ai's own GitHub page would go a long way for helping with this? I'd absolutely be happy for my code to be used there as an example. [This](https://github.com/Regular-Baf/bafchat/blob/master/src/main/kotlin/baf/chat/Bafmod3Sender.kt) is the part of my mod which handles the API call.

**Comment by louisgv** [comment]
Just enabled wiki: https://github.com/louisgv/local.ai/wiki

**Comment by louisgv** [comment]
See https://github.com/louisgv/local.ai/wiki/Using-the-local.ai-API
