### ISSUE TITLE
Support Metal inference

### ISSUE THREAD

**Issue by jonfairbanks** [louisgv/local.ai#4]
The latest version of llama.cpp has huge improvements on Mac hardware. 

Could this be implemented here as well?

https://github.com/ggerganov/llama.cpp/pull/1642

**Comment by louisgv** [comment]
Yup, it's based on top of ggml and although the rust implementation is a slight deviation fro llama.cpp, it's likely portable. We can use Rust macros to deliver an aarch64 dedicated GPU inferencing as well

**Comment by LLukas22** [comment]
Since https://github.com/rustformers/llm/commit/47a41c94c1063e6128ee5ba15acd8d47db7ac8dc Metal support is in the main branch for llama based architectures, it can be enabled by compiling with the `metal` --features flag and by setting use-gpu to true in the model-config.
