### ISSUE TITLE
Loading an `unknown` model leads to error

### ISSUE THREAD

**Issue by LLukas22** [louisgv/local.ai#44]
If i try to load an `unknown` model i get the following exception:
![image](https://github.com/louisgv/local.ai/assets/65088241/f14f6a56-7f81-47c9-adb3-e87b9514ae52)

If i load the same model via `llm` directly it works without problems.

**Comment by louisgv** [comment]
Whoops let me double check the model_stats config store, might have did something dumb in a previous push

**Comment by louisgv** [comment]
@LLukas22 should be fixed in the latest release 0.4.0 - pls reopen if you still see the error :d!
