### ISSUE TITLE
Code blocks are not escaped correctly

### ISSUE THREAD

**Issue by LLukas22** [louisgv/local.ai#52]
Code blocks don't seam to be escaped correctly:
![grafik](https://github.com/louisgv/local.ai/assets/65088241/748bda9b-b17b-45ae-946c-61e0fa8d0a37)

Generated text:

```python
def count_up(n): # function definition with n as parameter
 for i in range (2, (n+1)):  
 print((i))```

**Comment by louisgv** [comment]
@LLukas22 can you check the raw mdx file output to see if there's missing starting backticks?

**Comment by LLukas22** [comment]
I'll take another look tomorrow but i think the models just generated two ``` at the end of the code block 😅
