### ISSUE TITLE
Can not display the out put of model on windows. Please check it 

### ISSUE THREAD

**Issue by UnsGentoals** [louisgv/local.ai#6]
Can not display the out put of model on windows. 
Please check it 
And fix it.
Thanks 🙏

**Comment by louisgv** [comment]
@UnsGentoals can you send me a screenshot of the issue?

**Comment by UnsGentoals** [comment]
The first message was ingorned every time you restart the app.
Please check it.

**Comment by louisgv** [comment]
@UnsGentoals which model are you testing out btw? - There's a bug with non-llama model atm, I found a fix earlier will push a new version soon #9

**Comment by UnsGentoals** [comment]
airoboros 7b gpt4
 base on llama .

**Comment by louisgv** [comment]
@UnsGentoals are you using TheBloke's version? https://huggingface.co/TheBloke/airoboros-7b-gpt4-GGML/tree/main

**Comment by louisgv** [comment]
@UnsGentoals I just tested airoboros and it works on my end, make sure it's one of the non K-Quant version
