### ISSUE TITLE
WIKI | Add a guide on how to add a new model

### ISSUE THREAD

**Issue by louisgv** [louisgv/local.ai#76]

**Comment by tanmay-veer** [comment]
manually by selecting and downloading steps with screenshots would be sufficient ? Can you assign to me ?

**Comment by louisgv** [comment]
@tanmay-veer thanks for taking it up :D - please see the partial wiki here: https://github.com/louisgv/local.ai/wiki/HOWTO#testing-and-adding-a-new-model

We can either move it into a separate page, or put it in there as-is. Feel free to contribute however you like!
